### ISSUE TITLE
Fail to run `python train_act.py -c local `

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/trafficgen#9]
`python train_act.py -c local `

results in:

```bash
(tg) PS C:\Users\peng_\PycharmProjects\trafficgen> python train_act.py -c local 
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
C:\Users\peng_\.conda\envs\tg\lib\site-packages\pytorch_lightning\trainer\setup.py:176: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=1)`.
  rank_zero_warn(
loading data...
Traceback (most recent call last):
  File "train_act.py", line 33, in <module>
    train_set = actDataset(cfg)
  File "C:\Users\peng_\PycharmProjects\trafficgen\act\utils\act_dataset.py", line 252, in __init__
    self.load_data()
  File "C:\Users\peng_\PycharmProjects\trafficgen\act\utils\act_dataset.py", line 258, in load_data
    with open(data_path, 'rb+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'act/sample_data\\act_cache.pkl'
```

**Comment by Alan-LanFeng** [comment]
Thx for the report.
Fixed.
